### PR TITLE
Add web component elements and slot attribute

### PR DESCRIPTION
**Pull request by knpwrs**
The slot attribute is a standard attribute for use with web components: https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_templates_and_slots

### CODE REVIEW

**Comment by markuswustenberg** [comment]
Thanks! I don’t think we have the `template` and `slot` elements either?

**Comment by knpwrs** [comment]
I was thinking about that and couldn't think of a situation where I (in my workflow) would server-render `<template>` or `<slot>`. I can add them though, others may have a use-case.

**Comment by markuswustenberg** [comment]
D’oh, we run into a naming collision of course. Could you suffix each of `Slot` with `El` and `Attr`? And not add the non-suffixed version for now.

**Comment by knpwrs** [comment]
Should be all set now.

**Comment by markuswustenberg** [comment]
Thanks! Now just add them to the test tables and we’re set. 😊

**Comment by knpwrs** [comment]
Tests should be all set now

**Comment by markuswustenberg** [comment]
🥳

**Pull request merged**
